#pragma once

#define GPIO_TFT_DATA_CONTROL 6
#define GPIO_TFT_RESET_PIN 5
#define GPIO_TFT_BACKLIGHT 13
#define SPI_BUS_CLOCK_DIVISOR 20

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
